spring:
  application:
    name: banking-system
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/banking_system}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24h

logging:
  level:
    org.springframework.security: DEBUG
